# This is a basic workflow to help you get started with Actions

name: sendemail

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  sendemail:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Get custom email message with PR info
        uses: Devansh-Maurya/Get-Email-Message-From-Branch-Action@v3
        with:
    # Repository name
         repo-name: git-devops-assignment
    # Branch groups (as CSV) for which you want to get email message data
         groups: Group1
    # Branch name
         branch-name: master
         pr-title: ${{ github.event.pull_request.title }}
         pr-url: ${{ github.event.pull_request.html_url }}
         
